name: Tugtainer
version: "1.0.0"
slug: tugtainer
description: Docker container update automation with web UI
url: https://github.com/Quenary/tugtainer
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
hassio_api: true
hassio_role: manager
docker_api: true
host_network: false
ports:
  80/tcp: 9412
ports_description:
  80/tcp: Web interface
webui: http://[HOST]:[PORT:80]
ingress: true
ingress_port: 80
panel_icon: mdi:docker
map:
  - addon_config:rw
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: quenary/tugtainer
